#!/usr/bin/env bash

packages=(
  .
  packages/app-config
  packages/manifest
  packages/lib
  packages/data
  apps/discord
  apps/cli
)

for i in "${packages[@]}"
do
  if test -f "$i/.tmuxinator.yml"; then
    echo "Loading $i/.tmuxinator.yml"
    $(cd "$i" && tmuxinator start)
  fi
done

tmux -L degenz attach
