#!/usr/bin/env bash

packages=(
  .
  packages/config
  packages/manifest
  packages/lib
  packages/data
  apps/discord
  apps/web
  apps/cli
  apps/auth
  apps/minting-site
)

for i in "${packages[@]}"
do
  if test -f "$i/.tmuxinator.yml"; then
    echo "Loading $i/.tmuxinator.yml"
    $(cd "$i" && tmuxinator start)
  fi
done

tmux -L degenz attach
