#!/usr/bin/env bash

packages=(
  .
  packages/types
  packages/discord-config
  apps/discord
)

for i in "${packages[@]}"
do
  if test -f "$i/.tmuxinator.yml"; then
    echo "Loading $i/.tmuxinator.yml"
    $(cd "$i" && tmuxinator start)
  fi
done

tmux -L degenz attach
