import {
  BotSymbol,
  CategorySymbol,
  ChannelSymbol,
  RoleSymbol,
} from "data/types";

const GENERAL = {
  DISTRICT_CAPACITY: 2,
  GUILD_ID: "",
  PROD_GUILD_ID: "",
  READ_ONLY: false,
  SKIP_DELAY: false,
  USE_SCOUT: false,
  WORLD_NAME: "Beautopia",
};

const CATEGORY_IDS: Record<CategorySymbol, string> = {
  ADMIN: "",
  BEAUTOPIA: "",
  COMMAND_CENTER: "",
  COMMUNITY: "",
  ENTRANCE: "",
  JOIN_THE_GAME: "",
  OUTSIDE_WORLD: "",
  PRISON: "",
  THE_PROJECTS_D1: "",
  THE_PROJECTS_D2: "",
  THE_PROJECTS_D3: "",
  THE_PROJECTS_D4: "",
  THE_PROJECTS_D5: "",
  THE_PROJECTS_D6: "",
  THE_SHELTERS: "",
};

const CHANNEL_IDS: Record<ChannelSymbol, string> = {
  ADMIN_GENERAL: "",
  ADMIN_SANDBOX: "",
  ANNOUNCEMENTS: "",
  ARENA: "",
  ARMORY: "",
  BANK: "",
  BULLSEYE: "",
  COMMANDS: "",
  ENTER_THE_PROJECTS: "",
  ENTER_THE_SHELTERS: "",
  FAQ: "",
  FEEDBACK: "",
  GENERAL: "",
  GEN_POP: "",
  HALL_OF_ALLEIGANCE: "",
  HALL_OF_PRIVACY: "",
  LEADERBOARD: "",
  MART: "",
  METRO: "",
  ORIENTATION: "",
  TAVERN: "",
  THE_GRID: "",
  THE_LEFT: "",
  THE_RIGHT: "",
  TOSS_HOUSE: "",
  TOWN_SQUARE: "",
  TRAINING_DOJO: "",
  VERIFICATION: "",
  VULTURE: "",
  WAITING_ROOM: "",
  WELCOME_ROOM: "",
  WHITELIST: "",
};

const ROLE_IDS: Record<RoleSymbol, string> = {
  ADMIN: "",
  ADMIN_BOT: "",
  ALLY_BOT: "",
  ARMORY_CLERK_BOT: "",
  BANKER_BOT: "",
  BIG_BROTHER_BOT: "",
  DEGEN: "",
  DEVILS_ADVOCATE_BOT: "",
  EVERYONE: GENERAL.GUILD_ID,
  MART_CLERK_BOT: "",
  PRISONER: "",
  PRISONER_BOT: "",
  RESISTANCE_LEADER_BOT: "",
  SCOUT_BOT: "",
  SENSEI_BOT: "",
  SERVER_BOOSTER: "",
  THOUGHT_POLICE: "",
  TOSSER_BOT: "",
  TRAINEE: "",
  VERIFIED: "",
  WARDEN_BOT: "",
};

const CLIENT_IDS: Record<BotSymbol, string> = {
  ADMIN: "",
  ALLY: "",
  ARMORY_CLERK: "",
  BANKER: "",
  BIG_BROTHER: "",
  DEVILS_ADVOCATE: "",
  MART_CLERK: "",
  PRISONER: "",
  RESISTANCE_LEADER: "",
  SCOUT: "",
  SENSEI: "",
  TOSSER: "",
  WARDEN: "",
};

export default {
  CATEGORY_IDS,
  CHANNEL_IDS,
  CLIENT_IDS,
  GENERAL,
  ROLE_IDS,
};
