import { EnvVars } from "types";
import DEV_CONFIG from "./config";
import STAGE_CONFIG from "./config.stage";
import PROD_CONFIG from "./config.prod";

export const NODE_ENV =
  (process.env.NODE_ENV as "development" | "stage" | "production") ||
  "development";

const config = {
  development: DEV_CONFIG,
  stage: STAGE_CONFIG,
  production: PROD_CONFIG,
}[NODE_ENV];

export const {
  ADMIN_BOT_TOKEN,
  ALLY_BOT_TOKEN,
  BANKER_BOT_TOKEN,
  BIG_BROTHER_TOKEN,
  MART_CLERK_BOT_TOKEN,
  MIXPANEL_PROJECT_TOKEN,
  MONGO_URI,
  PRISONER_BOT_TOKEN,
  TOSSER_BOT_TOKEN,
  WARDEN_BOT_TOKEN,
  ROLLBAR_TOKEN,
} = process.env as EnvVars;

export const {
  ADMIN_BOT_CLIENT_ID,
  ADMIN_CATEGORY_ID,
  ADMIN_GENERAL_CHANNEL_ID,
  ADMIN_ROLE_ID,
  ADMIN_SANDBOX_CHANNEL_ID,
  ALLY_BOT_CLIENT_ID,
  ALLY_BOT_ROLE_ID,
  ANNOUNCEMENTS_CHANNEL_ID,
  ARMORY_CLERK_BOT_CLIENT_ID,
  ARMORY_CLERK_BOT_ROLE_ID,
  BANKER_BOT_CLIENT_ID,
  BANKER_BOT_ROLE_ID,
  BANK_CHANNEL_ID,
  BEAUTOPIA_CATEGORY_ID,
  BIG_BROTHER_BOT_CLIENT_ID,
  BIG_BROTHER_BOT_ROLE_ID,
  BOT_CLIENT_IDS,
  BUG_REPORTS_CHANNEL_ID,
  COMMANDS_CHANNEL_ID,
  COMMUNITY_CATEGORY_ID,
  DEGEN_ROLE_ID,
  DISTRICT_CAPACITY,
  EVERYONE_ROLE_ID,
  FAQ_CHANNEL_ID,
  GENERAL_CHANNEL_ID,
  GEN_POP_CHANNEL_ID,
  GUILD_ID,
  HALL_OF_PRIVACY_CHANNEL_ID,
  LEADERBOARD_CHANNEL_ID,
  LEADERBOARD_MESSAGE_ID,
  MART_CHANNEL_ID,
  MART_CLERK_BOT_CLIENT_ID,
  MART_CLERK_BOT_ROLE_ID,
  OUTSIDE_WORLD_CATEGORY_ID,
  PRISONER_BOT_CLIENT_ID,
  PRISONER_BOT_ROLE_ID,
  PRISONER_ROLE_ID,
  PRISON_CATEGORY_ID,
  SENSEI_BOT_CLIENT_ID,
  SENSEI_BOT_ROLE_ID,
  SERVER_BOOSTER_ROLE_ID,
  SKIP_DELAY,
  THE_ARENA_CHANNEL_ID,
  THE_ARMORY_CHANNEL_ID,
  THE_PROJECTS_D1_CATEGORY_ID,
  THE_PROJECTS_D2_CATEGORY_ID,
  THE_PROJECTS_D3_CATEGORY_ID,
  THE_PROJECTS_D4_CATEGORY_ID,
  THE_PROJECTS_D5_CATEGORY_ID,
  THE_PROJECTS_D6_CATEGORY_ID,
  TOSSER_BOT_CLIENT_ID,
  TOSSER_BOT_ROLE_ID,
  TOSS_CHANNEL_ID,
  TOWN_SQUARE_CHANNEL_ID,
  TRAINING_DOJO_CHANNEL_ID,
  VERIFICATION_CHANNEL_ID,
  VERIFICATION_MESSAGE_ID,
  VERIFIED_ROLE_ID,
  WARDEN_BOT_CLIENT_ID,
  WARDEN_BOT_ROLE_ID,
} = config;

export const WORLD_NAME = `Beautopia\u24b8`;
